name: Test and publish comment

on: [pull_request]

jobs:
  Time:
    runs-on: ubuntu-latest
    steps:
      - uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '2m' # for 1 minute

  publish:
    runs-on: ubuntu-latest
    needs: Time
    steps:
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            **This is a timer tester!!**
